## Домашнее задание №3

### Линейные преобразования

**1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей**

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

*Найдем собственные значения линейного оператора, решив характеристическое уравнение:*

 $$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)+6\cdot2=0,$$

$$\lambda^{2}-5\lambda+6=0,$$

$$\lambda_1=3,\,\lambda_2=2$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
a & b\\ 
c & d
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получаем

$$\begin{cases}
ax_{1}+bx_{2}=\lambda x_{1}, \\
cx_{1}+dx_{2}=\lambda x_{2}.
\end{cases}$$ 

Для $\lambda_1=3$:

### $$\begin{cases}
-x_{1}-6x_{2}=3x_{1}, \\
2x_{1}+6x_{2}=3x_{2}.
\end{cases}$$

### $$\begin{cases}
-4x_{1}-6x_{2}=0, \\
2x_{1}-4x_{1}+2x_{1}=0;
\end{cases}$$

### $$\begin{cases}
-4x_{1}=6x_{2}, \\
0=0;
\end{cases}$$

Система имеет множество решений вида вида $x=\begin{pmatrix}
C\\ 
-\frac{2}{3}C
\end{pmatrix}$, следовательно собственному значению $\lambda_1=3$ соответствует множество собственных векторов $x=\begin{pmatrix}
C\\ 
-\frac{2}{3}C
\end{pmatrix}$, где $C\neq0$.

Для $\lambda_2=2$:

### $$\begin{cases}
-x_{1}-6x_{2}=2x_{1}, \\
2x_{1}+6x_{2}=2x_{2}.
\end{cases}$$

### $$\begin{cases}
-3x_{1}-6x_{2}=0, \\
2x_{1}-3x_{1}+x_{1}=0;
\end{cases}$$

### $$\begin{cases}
-3x_{1}=6x_{2}, \\
0=0;
\end{cases}$$

**Система имеет множество решений вида вида** $x=\begin{pmatrix}
C\\ 
-\frac{1}{2}C
\end{pmatrix}$, **следовательно при $\lambda_2=2$ соответствует множество собственных векторов** $x=\begin{pmatrix}
C\\ 
-\frac{1}{2}C
\end{pmatrix}$, **где $C\neq0$.**

**Проверка с помощью numpyна Python**

In [1]:
import numpy as np

A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}\n')


Матрица A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]

Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]



In [2]:
x1=np.array([1, -2/3])
print(f'Cобственный вектор x1:\n{x1}\n')
print(f'Проверка x1 (A*x1=3*x1):\n{A.dot(x1)}={3*x1}\n')


Cобственный вектор x1:
[ 1.         -0.66666667]

Проверка x1 (A*x1=3*x1):
[ 3. -2.]=[ 3. -2.]



In [3]:
x2=np.array([1, -1/2])
print(f'Cобственный вектор x2:\n{x2}\n')
print(f'Проверка x2 (A*x2=2*x2):\n{A.dot(x2)}={2*x2}')

Cобственный вектор x2:
[ 1.  -0.5]

Проверка x2 (A*x2=2*x2):
[ 2. -1.]=[ 2. -1.]


### __Ответ:__ cобственные значения $3$, $2$; cобственные векторы $\begin{pmatrix}
C\\ 
-\frac{2}{3}C
\end{pmatrix}$, где $C\neq0$, $\begin{pmatrix}
C\\ 
-\frac{1}{2}C
\end{pmatrix}$, где $C\neq0$.

**2. Дан оператор поворота на 180 градусов, задаваемый матрицей:**

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

**Показать, что любой вектор является для него собственным.**

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

### $$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

### $$(-1-\lambda)^2=0,$$

### $$\lambda_{1,2}=-1.$$

Cобственные векторы:

### $$\begin{cases}
ax_{1}+bx_{2}=\lambda x_{1}, \\
cx_{1}+dx_{2}=\lambda x_{2}.
\end{cases}$$ 

### $$\begin{cases}
-x_{1}=-x_{1}, \\
-x_{2}=-x_{2}.
\end{cases}$$ 

**Ответ: Система имеет множество решений, а значит любой ненулевой вектор является собственным вектором оператора.**

**3. Пусть линейный оператор задан матрицей:**

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

**Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.**

Предположим, что $x$ является собственным вектором заданного линейного оператора, тогда должно существовать вещественное число $\lambda$, при котором:

### $$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Cледовательно: 

### $$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 =1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

Вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$ и его собственное значение составляет $\lambda=2.$

In [4]:
A = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}\n')

Матрица A:
[[ 1  1]
 [-1  3]]



In [5]:
print(f'Собственные значения:\n{w}\n')

Собственные значения:
[2.00000002 1.99999998]



In [6]:
print(f'Собственные векторы:\n{v}\n')

Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]



**Ответ: является.**

**4. Пусть линейный оператор задан матрицей:**

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

**Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.**

Предположим, что вектор $x$ является собственным этого заданного линейного оператора, тогда должно существовать вещественное число $\lambda$, при котором:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}.$$

Получененная система не имеет смысла, следовательно, вектор $x=(3,-3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [7]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]


In [8]:
print(f'Собственные значения:\n{w}')


Собственные значения:
[ 3. -3.  3.]


In [9]:
print(f'Собственные векторы:\n{v}')

Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


**Ответ: не является.